apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "oidc-gateway.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "oidc-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
